### ISSUE TITLE
Error in if (lastMonth == 2 & (lastYear%%4 == 0) & ((lastYear%%100 !=  :    missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by raruggie** [USGS-R/EGRET#357] opened 2023-01-13 23:07 UTC
I am getting the error in the title when trying to use the ```setupYears``` function. I have tried this for multiple sites ("USGS-01358000", Hudson River at Green Island, and "USGS-04213500", CATTARAUGUS CREEK AT GOWANDA NY) and get the same error. Could it be related to the fact that I have not trimmed down the flow data period of record to match the water quality data  period of record? 

Here is my code:

```
## set USGS site

s1<-"USGS-01358000"
s1_NWIS<-substr(s1, 6, nchar(s1)) # set a NWIS format site by removing the USGS prefix

## set flow and Nitrogen USGS Pcode

flow<-'00060'
Nitro<-'00631'

## download Daily, Sample, and Info dataframes using EGRET functions

Daily <- readNWISDaily(s1_NWIS, flow, startDate = "", endDate = "")
Sample<-readWQPSample(s1,Nitro,startDate="",endDate="")
INFO <- readNWISInfo(s1_NWIS,Nitro,interactive = FALSE)

## merge the Daily, Sample, and Info dataframes into an eList object

eList <- mergeReport(INFO,Daily,Sample)

# eList <- as.egret(INFO,Daily, Sample) # what is the difference between mergeReport and as.egret functions in the user manual?

## Run WRTDS model. 

mE <- modelEstimation(eList, windowY = 7, windowQ = 2, windowS = 0.5, minNumObs = 60, minNumUncen =50, edgeAdjust = TRUE) # default values other than minNumObs (100->60)

## compute an annual results df

AnnualResults<-setupYears(mE$Daily) # which gives the error: Error in if (lastMonth == 2 & (lastYear%%4 == 0) & ((lastYear%%100 !=  : missing value where TRUE/FALSE needed
```

Also, is there a difference between the ```mergeReport``` and ```as.egret``` functions for initiating ``eList```? I couldn't find an explanation in the EGRET user manual (https://pubs.usgs.gov/tm/04/a10/pdf/tm4A10.pdf).

**Comment by rmhirsch49** [comment] 2023-01-14 20:03
Thanks for the question.  I think it is a great example of why it is best when starting out on a data set to do things interactively.  There were two problems here that would show up quickly in an interactive session and then could be fixed leading to having an eList that doesn’t have any problems.

The two problems here are:

  1.  A bunch of gaps in the discharge record (but that turned out to be ok because they were all after the end of the water quality record so we didn’t need them)
  2.  The specified discharge record is way too long given the shortness of the water quality record.

Both of these issues are best fixed by looking at the record and setting the startData and endDate appropriately.

I’m curious as to why you are using readWQPSample() rather than readNWISSample().  The water quality data are in NWIS.  We have found that there are a number of issues that come up when NWIS data are in the Portal.  Some of the information in the NWIS data set doesn’t make it to the Portal.  People are working on solving these problems, but there is still work to be done on that.  My advice for now is this: If your water quality data are in NWIS then use readNWISSample().

See my commented script attached.

Bob Hirsch


***********************************************
Robert M. Hirsch, Research Hydrologist Emeritus
430 National Center
U.S. Geological Survey         ***@***.******@***.***>
Reston, VA 20192

Profile<https://www.usgs.gov/staff-profiles/robert-m-hirsch> / publications<https://scholar.google.com/citations?user=bbfffD4AAAAJ&hl=en>/ EGRET software<https://gcc02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fusgs-r.github.io%2FEGRET&data=04%7C01%7Crhirsch%40usgs.gov%7C1249efb6b30d4afb06b308d904fe48ff%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637546312517236793%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=GcQZL%2ByZBYUcdELS1dMF4%2F5kR86EQ%2FuppBcXm0u1Sak%3D&reserved=0>
Statistical Methods in Water Resources<https://store.usgs.gov/product/533012>
************************************************




From: raruggie ***@***.***>
Date: Friday, January 13, 2023 at 6:07 PM
To: USGS-R/EGRET ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [USGS-R/EGRET] Error in if (lastMonth == 2 & (lastYear%%4 == 0) & ((lastYear%%100 != : missing value where TRUE/FALSE needed (Issue #357)



 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



I am getting the error in the title when trying to use the setupYears function. I have tried this for multiple sites ("USGS-01358000", Hudson River at Green Island, and "USGS-04213500", CATTARAUGUS CREEK AT GOWANDA NY) and get the same error. Could it be related to the fact that I have not trimmed down the flow data period of record to match the water quality data period of record?

Here is my code:

## set USGS site



s1<-"USGS-01358000"

s1_NWIS<-substr(s1, 6, nchar(s1)) # set a NWIS format site by removing the USGS prefix



## set flow and Nitrogen USGS Pcode



flow<-'00060'

Nitro<-'00631'



## download Daily, Sample, and Info dataframes using EGRET functions



Daily <- readNWISDaily(s1_NWIS, flow, startDate = "", endDate = "")

Sample<-readWQPSample(s1,Nitro,startDate="",endDate="")

INFO <- readNWISInfo(s1_NWIS,Nitro,interactive = FALSE)



## merge the Daily, Sample, and Info dataframes into an eList object



eList <- mergeReport(INFO,Daily,Sample)



# eList <- as.egret(INFO,Daily, Sample) # what is the difference between mergeReport and as.egret functions in the user manual?



## Run WRTDS model.



mE <- modelEstimation(eList, windowY = 7, windowQ = 2, windowS = 0.5, minNumObs = 60, minNumUncen =50, edgeAdjust = TRUE) # default values



## compute an annual results df



AnnualResults<-setupYears(mE$Daily) # which gives the error: Error in if (lastMonth == 2 & (lastYear%%4 == 0) & ((lastYear%%100 !=  : missing value where TRUE/FALSE needed

Also, is there a difference between the mergeReport and as.egret functions for initiating ``eList```? I couldn't find an explanation in the EGRET user manual (https://pubs.usgs.gov/tm/04/a10/pdf/tm4A10.pdf).

**Comment by raruggie** [comment] 2023-01-14 22:35
Bob Hirsch,
Thank you for the response. I don't see any attached code to this github posting, nor was there a file attached to the emailed version of your response to my inbox. However, when I adjusted the start and end dates I no longer got the error, thank you. Just to clarify, when you say an interactive session, you mean to use some data visualization functions (e.g. ```multiPlotDataOverview(eList)```) to look at the data?

I don't understand from your response what the issue is with using ```readWQPSample()```. As to why I am using ```readWQPSample()```, I was told by Laura DeCicco that in the dataRetrieval package, water quality data downloading was no longer going to be possible using any of the NWIS flavored functions (see https://github.com/DOI-USGS/dataRetrieval/issues/643). I assumed the same discontinued use of NWIS functions for water quality data carried over into EGRET? 

-Ryan

**Comment by rmhirsch49** [comment] 2023-01-15 14:07
Ryan: I forgot that github doesn’t allow me to attach files to a response.  I’ve pasted the content in below.

What I mean by interactive is that you are able to see messages from EGRET as you go and that you can explore what is going on.  When I did your original code I got messages on my console telling me about the many data gaps, that caused me to start exploring questions such as:  Are the gaps in the discharge data during a period of time when there are samples.  I answered that by running the readNWISSample() and then doing summary(Sample) and that showed me when my first and last observations happened.  My point here is that there are many things that can be problematic when retrieving a data set and creating an eList.  For that reason I need to use a variety of EGRET and base R functions to help me figure out what is going on.  You will see some of that in my code below.  The graphics can also be very useful, such as multiPlotDataOverview() that’s what told me that there is this big gap in the data.  So, what I mean by interactive is: 1) seeing the messages generated and acting on that information, 2) exploring the data retrieved to understand its features, and 3) using various EGRET graphical functions to see what’s happening.  Once you have a clean eList, then using a script is typically fine, but I generally go interactive when I’m creating the eList.

Regarding readNWISSample and readWQPSample, Laura and I and others have recently identified situations where we get different results for the same data set.  I think the problems have to do with censored data, but there is also a problem with some data sets getting re-ordered (i.e. the Sample data frame doesn’t always progress from oldest to newest).  Laura and others are working to resolve those issues.  She is correct that readNWISSample is supposed to go away some time in the future, but for now, I personally would avoid using the WQP functions for now for cases where the data are in NWIS.  I just checked and it appears that both of these functions give the same result with this data set, but in general I am not confident about readWQPSample() at the present time.

Bob Hirsch

Content of my script below


# I played around with your code and saw two issues
# There are many gaps in the discharge record, starting in 1997 and ending in 2022
# EGRET won't really work with any gaps in the discharge record
# I like running things interactively so I can see these problems and deal with them when I'm creating my eList
# the other problem is that the sample data cover only water years 1973 through 1994
# that means you should probably just retrieve discharge data for those water years
# and that means that the missing discharge record is no problem
# I suggest you run readNWISSample() first and then based on that run readNWISDaily()
# I don't like readWQPSample() if you are working with NWIS data.  There are some problems in the WQP
# here's my work flow (after your code that sets up station and parameter information)
Sample <- readNWISSample(s1_NWIS, Nitro)
Daily <- readNWISDaily(s1_NWIS, flow, startDate = "1972-10-01", endDate = "1994-09-30")
INFO <- readNWISInfo(s1_NWIS, Nitro, interactive = FALSE)
eList <- mergeReport(INFO, Daily, Sample)
# you asked about as.egret().  It just puts the files together into a named list
# it doesn't merge the discharge data from Daily into the Sample data frame
# mergeReport does that, then creates the named list (eList) and reports some basic statistics
# I would also add the multiPlotDataOverview() to see if things look sensible
multiPlotDataOverview(eList)
# when I saw what the data set looked like I decided that the gap between 1974 and 1980 was just
# too big, I don't want to try to span all of that, so I'm going to redo the retrieval for a narrower period
Sample$Date[1:20]
# what I see is 5 samples from May through September of 1973 - I don't think we want to use them
# there are so few and they only cover 5 months of the year
# so let's start again
Sample <- readNWISSample(s1_NWIS, Nitro, startDate = "1979-10-01", endDate = "1994-09-30")
Daily <- readNWISDaily(s1_NWIS, flow, startDate = "1979-10-01", endDate = "1994-09-30")
eList <- mergeReport(INFO, Daily, Sample)
multiPlotDataOverview(eList)
# now I'm satisfied that I have a pretty good data set to work with
# (maybe a couple of low outliers) but I don't think they will mess things up too badly
eList <- modelEstimation(eList, minNumObs = 50) # data set is only 78 samples so we need to set minNumObs < 78

From: raruggie ***@***.***>
Date: Saturday, January 14, 2023 at 5:35 PM
To: USGS-R/EGRET ***@***.***>
Cc: Hirsch, Robert M ***@***.***>, Comment ***@***.***>
Subject: [EXTERNAL] Re: [USGS-R/EGRET] Error in if (lastMonth == 2 & (lastYear%%4 == 0) & ((lastYear%%100 != : missing value where TRUE/FALSE needed (Issue #357)



 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Bob Hirsch,
Thank you for the response. I don't see any attached code to this github posting, nor was there a file attached to the emailed version of your response to my inbox. However, when I adjusted the start and end dates I no longer got the error, thank you. Just to clarify, when you say an interactive session, you mean to use some data visualization functions (e.g. multiPlotDataOverview(eList)) to look at the data?

I don't understand from your response what the issue is with using readWQPSample(). As to why I am using readWQPSample(), I was told by Laura DeCicco that in the dataRetrieval package, water quality data downloading was no longer going to be possible using any of the NWIS flavored functions (see DOI-USGS/dataRetrieval#643<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDOI-USGS%2FdataRetrieval%2Fissues%2F643&data=05%7C01%7Crhirsch%40usgs.gov%7Ceab0d8f07a384cd5c82308daf67f9fd8%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638093325257363810%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=LHD5wcbnU6g5%2BrKzScB%2FSkJm20StqGnUA8vONWoJreU%3D&reserved=0>). I assumed the same discontinued use of NWIS functions for water quality data carried over into EGRET?

-Ryan

**Comment by raruggie** [comment] 2023-01-15 21:59
Bob,
Thank you for the response. I am still confused because I thought WQP included all the data sources for a site (e.g. EPA, state, NWIS) where as water quality data from NWIS would just be samples taken by the USGS. How I can tell if a site has its better data on WQP or through NWIS (i.e. better quality and quantity)? Would I need to run both functions and look at the resulting data frames?

I just wanted to make sure: it is okay to use NWIS functions for water quality data if they are part of the EGRET package, but what Laura said about dataRetrieval is still accurate, i.e. don't use NWIS and use the WQP functions? For example, would you trust this code for finding sites in New York that have Nitrogen data?:

```
library(dataRetrieval)
Nitro<-'00631'
NY_sites_N<- whatWQPdata(statecode = '36', 
                         parameterCd = Nitro,
                         siteType="Stream")
```

I would then use the list of these sites with EGRET functions to find trends for each site. Does this sound okay?

-Ryan

**Comment by rmhirsch49** [comment] 2023-01-16 01:29
Ryan, let me try to clarify.

First of all, the data in WQP contains NWIS data and data from many other sources (I wouldn’t say “all the data sources”). NWIS data are a subset of what is in WQP.  I notice that you mention looking for nutrient data in New York.  I happen to know that as of a couple of years ago the water quality data collected by New York City DEP in the New York City watershed were in neither system.  My point here is that sometimes it is important to reach out to many agencies to try to make sure that you are capturing a large fraction of all the data that exist.  The WQP is a great advancement, but it still doesn’t have “all data sources.”

The issue I was pointing to is that we know there are at least a couple of kinds of “glitches” in the way NWIS data are captured and stored in the WQP.  For that reason, if I knew that the data I want to get is in both NWIS and WQP then I would have a preference for going to NWIS.  I hope these problems get resolved soon, but for now, that is what I would do.  Go with readNWISSample() rather than readWQPSample() if the data are in NWIS.

I’m not sure I understand what you mean by “for water quality data if they are a part of the EGRET package”.  There are no data in EGRET, there are only functions.  As I said above, it the data are of interest are in NWIS then I would use the EGRET function readNWISSample() to retrieve them.  I’m not sure what Laura may have said to you, but I think she was focused on a time in the future (no timeline exists for this right now) when the function readNWISSample() will go away.  Then there will only be two ways to get water quality data into an EGRET analysis.  One will be readWQPSample() and will be readUserSample(). (the latter is used for a situation where the data are not in the WQP but exist in a .csv file).

I’m not an expert at using dataRetrieval but the code you showed below looks like the right way to do an inventory.  The information you get from this NY_sites_N should have a field that tells you what agency collected it.  (In EGRET that is eList$INFO$agency_cd).   If it says it was USGS then my preference would be to use readNWISSample() for those and use readWQPSample() for all of the others.  After you bring in the data then every other step in the analysis will be the same regardless of how you obtained the data.

In summary, what Laura is telling you is exactly right, for some time out in the future.  What I’m telling you is what I would do if I were going to run an analysis TODAY.  (Laura I hope you will chime in here).

Bob Hirsch

From: raruggie ***@***.***>
Date: Sunday, January 15, 2023 at 4:59 PM
To: USGS-R/EGRET ***@***.***>
Cc: Hirsch, Robert M ***@***.***>, Comment ***@***.***>
Subject: [EXTERNAL] Re: [USGS-R/EGRET] Error in if (lastMonth == 2 & (lastYear%%4 == 0) & ((lastYear%%100 != : missing value where TRUE/FALSE needed (Issue #357)



 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Bob,
Thank you for the response. I am still confused because I thought WQP included all the data sources for a site (e.g. EPA, state, NWIS) where as water quality data from NWIS would just be samples taken by the USGS. How I can tell if a site has its better data on WQP or through NWIS (i.e. better quality and quantity)? Would I need to run both functions and look at the resulting data frames?

I just wanted to make sure: it is okay to use NWIS functions for water quality data if they are part of the EGRET package, but what Laura said about dataRetrieval is still accurate, i.e. don't use NWIS and use the WQP functions? For example, would you trust this code for finding sites in New York that have Nitrogen data?:

library(dataRetrieval)

Nitro<-'00631'

NY_sites_N<- whatWQPdata(statecode = '36',

                         parameterCd = Nitro,

                         siteType="Stream")

I would then use the list of these sites with EGRET functions to find trends for each site. Does this sound okay?

-Ryan

**Comment by raruggie** [comment] 2023-01-16 16:26
Bob,
Thank you, I'm sorry for the confusion in my last comment. This clarify things. 
-Ryan

**Comment by ldecicco-USGS** [comment] 2023-01-16 19:08
Sorry I was on leave last week and couldn't contribute to the conversation. 

To expand on Bob's points:

The "NWIS" functions are still working. At one point, we were told they were going to be shut down imminently, but the date for that shut-down continues to be pushed back. USGS data itself should be identical between NWIS and WQP (not including the formatting), however we've recently discovered a few sites that are not including some censoring limits which is very important for EGRET analysis. The mapping from our legacy NWIS system to the WQP format is being updated so those censoring values will be there in the (hopefully near) future. So in the meantime, I'd just recommend sticking with readNWISsample. We'll do a pretty heavy outreach campaign when we know for sure when the NWIS qw services will be shut down. The other difference with WQP vs NWIS is that WQP doesn't sort the data by measurement date. We've added that sorting to EGRET. To get that update you'd need to be using the GitHub version of EGRET though (not what's currently on CRAN).


You can use the `whatWQPdata` function as you described. For any USGS site, you can strip the "USGS-" from the monitoring location and get the sampling data from readNWISSample. For any site (USGS or otherwise), you'll need to think about where to get the discharge record. USGS discharge will continue to be available from the readNWISDaily function.

I'm leaving this Issue as active so I can see if I can make the error message in setupYears more clear for the situation you described. Thanks for reporting it!

**Comment by ldecicco-USGS** [comment] 2023-01-18 19:09
I thought I'd expand on the answer for finding "all the data" (ie, if you were looking for all the nitrogen in NY):

If you are looking for "all-the-data", pcode is not the way to go, you'll only find USGS sites if you specify the query based on a parameter code. 

I've been working on another project where we create water quality reports based on a shapefile (in the specific package, it is a FWS Wildlife Refuge, but we could tweek it to more general shapefiles with a little work).

https://rconnect.usgs.gov/wqReport

The way we define "all-the-data" in that project was a parameter lookup file:
https://rconnect.usgs.gov/wqReport/articles/customize_report_data.html#custom-parameter-lookup-file

We define characteristic name, sample fraction, and unit to be one "set", and we offer unit conversions to get more data to group together if it's appropriate (ie a simple unit conversion mg/l to ug/l for instance).

I could see where you might then take this data and do WRTDS analysis... finding the appropriate discharge measurements might end up taking a lot of time/effort. I'm showing you these examples because they might be useful to see how others group water quality data.

**Comment by ldecicco-USGS** [comment] 2023-01-24 16:16
FYI if you use the GitHub version of EGRET (and soon will be pushed to CRAN), you will see a more informative message:
```r
Error in setupYears(mE$Daily) : 
  Daily dataframe cannot have gaps in the data.
```

**Closed by ldecicco-USGS** 2023-01-24 16:16 UTC
